# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6629ac43d9f1939b269e9696831b71fefde55a8b48751116f55104e1f0b94da8b9cac92654c3cfc4d7546638e0cbdf7fece138f3ccaba89eb0d6b29b7bdc143c

test:
  secret_key_base: 70fbfd0e2153e2ade0daf585614fb601b6fb8c44cf3e20095e84b990696836de15ba1c7aea131af49dcd61bc8b3ccd8181f350f3a6520bd36291184c058bd2f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
